[package]
name = "componentize-py-runtime"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
anyhow = "1.0.87"
once_cell = "1.19.0"
pyo3 = { version = "0.22.2", features = ["abi3-py312", "num-bigint"] }
componentize-py-shared = { path = "../shared" }
num-bigint = "0.4.6"
wit-bindgen = "0.16.0"
